### ISSUE TITLE
Syncing / listening

### ISSUE THREAD

**Issue by Wandelstock** [SchildiChat/SchildiChat-android#1]
Hi there, nice fork! But is it possible to disable the listening/syncing icon (or make an option to disable it), it is a lot visible

![IMG_20200808_210546_260.jpg](https://user-images.githubusercontent.com/58773587/89717900-0f7a3380-d9bb-11ea-81a5-49d108b26ac2.jpg)

**Comment by SpiritCroc** [comment]
Unfortunately, due to Android background execution limitations, the notification is necessary to ensure that Android doesn't kill the app and thus to ensure message notifications, so I don't think it is a good idea to disable the notification from within the app. In recent Android versions (at least in Android 10, I don't remember when it got introduced), it is possible to disable the listening notification from the system settings, however.

**Comment by Wandelstock** [comment]
Strange that on the same device where Element is installed it doesn't show.

**Comment by SpiritCroc** [comment]
That might be because SchidliChat right now does not use the google push notification mechanism, while Element (if installed from the Play Store) does. I'm currently investigating means of enabling push notifications for SchildiChat as well.

**Comment by SpiritCroc** [comment]
I pushed a new release to the [beta channel](https://play.google.com/apps/testing/de.spiritcroc.riotx) on google play (version sc.11) with hopefully working push notifications, if you want, you can test it once it's up and reports if it's better

**Comment by Wandelstock** [comment]
I will let you know

**Comment by Wandelstock** [comment]
Works great! Not slower or faster than Element. Tomorrow i do a battery test, looking how much it uses.

**Comment by Wandelstock** [comment]
No extra battery usage

**Comment by SpiritCroc** [comment]
Since push notifications are now included in google play store releases, and other syncing/listening issues would also apply to upstream, I assume this can be closed now.
