### ISSUE TITLE
GitHub Releases APK

### ISSUE THREAD

**Issue by noClaps** [SchildiChat/SchildiChat-android#126]
I was wondering if its possible for APKs to be signed and released on GitHub Releases. I use a degoogled phone, so I'm unable to use the Play Store. As for F-Droid, I'd prefer it if we could have developer-signed APKs so that I only have to trust one party instead of 2.

If this isn't possible, I understand.

**Comment by su-ex** [comment]
https://schildi.chat/android/
What about using the SpiritCroc F-Droid repo?
There are also direct links to the apks, if you prefer that.

**Comment by SpiritCroc** [comment]
(Note that the SpiritCroc F-Droid repo provides "developer-signed APKs", if that wasn't clear)

I'd also recommend using our F-Droid repo for the sake of updates, downloading APKs manually for each update sounds cumbersome.

Oh, and as a side-node, releases in the Google Play Store are no longer developer-signed either, since Google forced us to use their app bundle mechanism for which Google signs the app... so if you really care about a developer signature, better use SchildiChat[f] (or SchildiChat[g] if you want FCM push, but I guess you don't want on a degoogled phone) instead of the one without brackets from our repo - since the one without brackets is compatible with the Google Play Store version, for which Google has the signing key as well.

**Comment by noClaps** [comment]
I have GitHub Releases atom feeds set up for my open source apps so that I can update as soon as it releases. I'm fine downloading the APK from the website linked above, but I imagine you don't have an RSS/Atom feed set up for updates to that.

As for F-Droid, I'd be installing it just for SchildiChat since I have all of my other apps already set up with the Atom feed.

If this is not possible please let me know and close this issue. Thanks!

**Comment by su-ex** [comment]
You can get the release tags as rss feed: https://github.com/SchildiChat/SchildiChat-android/tags.atom
You can also join this matrix room for release announcements: [#android-announcements:schildi.chat](https://matrix.to/#/#android-announcements:schildi.chat)

**Comment by noClaps** [comment]
Alright I'll look at other options.

Thanks anyway!
