### ISSUE TITLE
Howto: Set up SchildiChat with UnifiedPush (Gotify-UP) to receive messages instantly 

### ISSUE THREAD

**Issue by krei-del** [SchildiChat/SchildiChat-android#127]
Hello,

I'm happy to use SchildiChat with UnifiedPush, but with my test I could not get a setup for non-delay messages, even with UnifiedPush set up. Primarily between mobile devices.

Example: After haven't used the mobile for while I did sent a message from a another phone, it did not show up. But I'm not sure I missed some important setting.

Can someone provide instructions how to set up SchildiChat with UnifiedPush to receive messages instantly? (That not working is the biggest downside for family and friends).

My current understanding:
1) Install App SchildiChat (FOSS)
2) Install App Gotify-UP
3) Define URL, User and Pass for Gotify-UP. 

- Does every Mobile Client needs its own User and Password? (I guess so)
- Or can everyone share same user and password but does register several devices 
- (Offtopic: Is necessary to explicitly set up Gotify with SchildiChat under Linux Desktop System?)

4) Register push distributor within SchildiChat

Is this correct? What else is there to do?
- Free SchildiChat and Gotify-UP from "Battery Optimizations" that they can work in background constantly?
- Is it necessary to run Gotify-UP explicitly after each reboot or is it more used like a library as soon as SchildiChat starts off?
- More settings?

Thanks for any support!
![Screenshot_20220603-161310_SchildiChat](https://user-images.githubusercontent.com/67123155/171875762-28bd360e-9330-44c5-9b36-f8359f7f695a.png)
![Screenshot_20220603-162806_SchildiChat](https://user-images.githubusercontent.com/67123155/171875775-3f22cbd9-da5e-4199-9907-6694f1e467b5.png)

**Comment by SpiritCroc** [comment]
For notification troubles, please also check what Settings/Notifications/Troubleshoot notifications shows.

Not every client or device needs their own user / password. Gotify is not ideal in the setup of multiple devices though, since it will post you duplicate notifications, which you can disable however from the Android settings. If you want a push solution without user/password management, ntfy is likely a better choice than gotify.

Gotify-UP is required to run its background service, so you should allow it to auto-start, and maybe remove it from battery optimizations if you have notification issues.

**Comment by sigma2017** [comment]
Both  Element or SchildiChat are loosing connectivity to synapse server, that's why almost all the time I am not able to see notifications doesn't matter the settings related to battery optimization and so on.. Most of the times I have to manually open the application in order to see the received messages. Same applies with the calls, you can NOT rely on it. You have to use another messenger to announce your friend that you gonna chat or call him on SchildiChat. Once the application is open and somehow the connectivity is re-established with the server, you can call and the call is working.  This is not happening with element android, in most of the tries, the caller remain in "calling" and the other phone remain in "connecting" after his answered to the call.   That's why I am using SchildiChat because at least I can trust that I will be able to have a audio or video call with a friend. Is clear that this is a big step ahead for SchildiChat when compared with the former Element app.
I am using one synapse server deployed on a vps with coturn integrated. Is not a server issue when it comes to notification because for example FluffyChat never miss a notification because somehow it never loose the server connectivity. How it does? I really don't know. Unfortunately fluffychat has some other bugs...
I hope you got my point here, I can NOT rely on SchildiChat because almost all the time i miss either messages or calls.
This is he biggest issue SchildiChat (and Element) have. Thank you.

**Comment by su-ex** [comment]
ntfy is now preferred, also read the FAQ: https://schildi.chat/android/faq/
(search results put this issue on top)
