### ISSUE TITLE
Anti-Features ?

### ISSUE THREAD

**Issue by caywin25** [SchildiChat/SchildiChat-android#130]
Hello,

On fdroid page : https://f-droid.org/packages/de.spiritcroc.riotx/ we can see this message in bottom of page : 

```
Anti-Features
This app has features you may not like. Learn more!

This app promotes or depends entirely on a non-free network service
```

What are these anti functions, please?
What does that mean?
Thank you

**Comment by SpiritCroc** [comment]
This comes from Element's "Integration manager" implementation. Since this integration manager is currently hardcoded to https://scalar.vector.im, which is closed source and thus cannot be self-hosted right now, this leads to said anti-feature. I'm not really happy with that approach either. However, that feature should be off by default, so shouldn't cause any privacy issues while off.

For reference: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11142

**Comment by caywin25** [comment]
Perfect, thank you :ok_hand:

**Comment by shuvashish76** [comment]
> I'm not really happy with that approach either.

https://gitlab.com/fdroid/fdroiddata/-/issues/3048

![SchildiChat](https://github.com/SchildiChat/SchildiChat-android/assets/48226312/ea4617f5-3702-43a7-bc99-31ff15535f18)
@SpiritCroc Disabled by default which is nice. Would be nice if you mention that "⚠️This service is proprietary." or something similar in the description for transparency because we don't expect users to search GH issue tracker for that.

One F-Droid maintainer said
> Sylvia: I myself definitely thought the Integration Manager was FOSS until someone told me it wasn't and I had to search for hours to find an obscure comment on a random issue stating that, yes, it's proprietary.

**Comment by SpiritCroc** [comment]
Good idea, done in https://github.com/SchildiChat/SchildiChat-android/commit/16ccd7817f20a86042a21dba6d9a0766d6781a8e :+1: 

![Screenshot_2023-07-30_19-50-37](https://github.com/SchildiChat/SchildiChat-android/assets/12481742/75db927d-1dd5-439c-bf9b-9f3750dd7684)
