### ISSUE TITLE
pseudo highlight

### ISSUE THREAD

**Issue by caywin25** [SchildiChat/SchildiChat-android#16]
Hello, 

When I highlight a pseudo, I can see that the exact url is: 
> https://matrix.to/#/@pseudo:homeserver

Is it possible to make a simple highlight without calling matrix.to?
Thank you !

**Comment by SpiritCroc** [comment]
I don't think it automatically calls matrix.to just because the text contains it.
Furthermore, since this behavior needs to be identical across multiple matrix clients, it's probably best to not change the client unless there's something in the matrix spec for this. I guess this would be interesting: https://github.com/matrix-org/matrix-doc/pull/2312
