### ISSUE TITLE
crash when creating new matrix.org account

### ISSUE THREAD

**Issue by defini-tiv** [SchildiChat/SchildiChat-android#162]
**Describe the bug**

When trying to create a new account, app crashes afer solving captcha.

**To Reproduce**
1. Choose the pictures asked by the captcha
2. Click on 'select' ("auswählen" in german)
3. App crashes

**Comment by SpiritCroc** [comment]
Thanks for reporting! I actually fixed this yesterday in https://github.com/SchildiChat/SchildiChat-android/commit/cf0dc42020b3d3e79e7e0bb6035808231da6b42f , so it will be fixed in the next release (unfortunately, doing another release is currently blocked by https://github.com/vector-im/element-android/issues/7557 ).

Please include the app version next time you report a bug though.
