### ISSUE TITLE
Voice message breaks off after two minutes or doesn't continue

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#167]
**Describe the bug**
Voice message breaks off after two minutes or doesn't continue

**To Reproduce**

A recording is started.  The recording time is running.  After two minutes, the message is sent without you noticing anything.  It just stops recording.

**Comment by SpiritCroc** [comment]
Should have linked the upstream issue https://github.com/vector-im/element-android/issues/4160

**Comment by SpiritCroc** [comment]
Reasons why I'd rather not blindly increase the limit, but rather follow upstream, given in https://github.com/vector-im/element-android/pull/6738

**Comment by sphuo5g** [comment]
Off topic @ stale bot: https://drewdevault.com/2021/10/26/stalebot.html

**Comment by SpiritCroc** [comment]
> Off topic @ stale bot: https://drewdevault.com/2021/10/26/stalebot.html

We did not install stale bot because github made us do it. It was a conscious decision and it makes our lives easier. We also have a fair share of labels that exempt stale bot from doing anything. Please check our configuration and give us constructive feedback if you think there's something that needs improving.
If the issue has been without activity as long as it was, chances are high nobody was thinking about it and I will not ever touch it anyways. So stale bot reminds me to have a look, or it will close it as something that will not receive any updates anyways. If an issue is out of scope for this project / for me to implement, seems totally legit to me to close it. Feel free to do a PR anyways if this issue bothers you, closing it does not equal to wontfix and does not prevent anyone from re-opening it.

(Maybe also keep in mind "community contribution" that your article mentions is relatively low for this project... it would make more sense if this were a bigger project and not depend on upstream/Element anyways)
