### ISSUE TITLE
Long delay for calls to ring when using background sync

### ISSUE THREAD

**Issue by reh9** [SchildiChat/SchildiChat-android#175]
1.5.8.sc62 [40100990] (F-39aff9f2)
1.5.8 (39aff9f2)
Olm version 3.2.12

I am using FOSS version.
When initiating a call sometimes it takes very long time before other side actually starts ringing, sometimes it never rings and the info is given to the caller the other side did not pick up.

I found out that lowering the **"Delay between each sink"** value from default 60s to 15s solves the issue.

Would it be possible to decrease the default value to 15s or at least 30s? This would make it much easier to recommend the app to non-tech people. I understand this increases power consumption but otherwise the app is almost unusable.

**Comment by SpiritCroc** [comment]
I'd rather recommend you to look into a push solution. Either your non-tech friends are using the Google variant either way and thus get FCM push notifications, or you may want to look into UnifiedPush. Reducing the sync interval has the risk that Android will kill the app due to too much background activity, which will only make the situation worse.
