### ISSUE TITLE
permission_ change WebSite to https://schildi.chat/android

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#205]
* at present [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/de.spiritcroc.riotx.yml) lists https://schildi.chat  as WebSite
* is it **ok to change** WebSite link to https://schildi.chat/android, specific to android app only?

**Comment by SpiritCroc** [comment]
Fine with me

**Comment by ghost** [comment]
@SpiritCroc 
updated in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549
* thank you

**Comment by SpiritCroc** [comment]
@jindam-vani 

Thanks for adding the translation link!

Some note, since I see
```
Changelog: https://github.com/SchildiChat/SchildiChat-android/blob/sc/CHANGES.md
```
added:  
That one is just the plain Element changelog which we don't touch, so doesn't make much sense to link here. We do have some changelogs in [the fastlane folder](https://github.com/SchildiChat/SchildiChat-android/tree/sc/fastlane/metadata/android/en-US/changelogs), but they aren't really userfriendly in the source form, so not sure if it makes sense to link at all

**Comment by ghost** [comment]
> added: That one is just the plain Element changelog which we don't touch, so doesn't make much sense to link here.

@SpiritCroc
* thanks for clarification
* yes, it doesnt make sense to include them
* will remove it at earliest possible time

**Comment by ghost** [comment]
* Changelog is removed in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13599
* thank you
