### ISSUE TITLE
mislabled setting ?

### ISSUE THREAD

**Issue by theotheroracle** [SchildiChat/SchildiChat-android#212]
**Describe the bug**
the "do not click this setting" does not describe what it does, but it seems to reset settings or something of the sort ? 

**Expected behavior**
it should either describe what it does, or not be present in release builds ?

**Additional context**
 - App version: 1.6.6.sc73 [40101232] (F-3a7b2e8d)
 - Store: F-Droid

**Upstream relevance**
 - Does this issue exist in Element Android?
 no

**Comment by SpiritCroc** [comment]
No, you should just not click it.

**Comment by theotheroracle** [comment]
if theres an option called "dont click me" people are going to click it :/

**Comment by xeniarose** [comment]
release builds of software should not troll their own users with destructive actions that are easy to trigger without knowing and not possible to undo. that's extremely user-hostile default behavior

**Comment by SpiritCroc** [comment]
> if theres an option called "dont click me" people are going to click it :/

Yeah, I will not stop you from doing so if you really want to - just note it will do nothing useful to you

> release builds of software should not troll their own users with destructive actions that are easy to trigger without knowing and not possible to undo. that's extremely user-hostile default behavior

It's not meant for trolling. This is a setting that changes the default settings to my preferred settings. As developer, I do fresh installs way more often than normal users, so this really increases my productivity, if I don't have to re-setup everything all the time. Granted I could have hidden it in some other way, but I didn't have a good idea at the time and I can spend my time on more meaningful things as well.

I would argue that it's not easy to trigger by mistake since it will launch a dialog asking whether you really want to continue.

**Comment by Marie-Joseph** [comment]
> It's not meant for trolling. This is a setting that changes the default settings to my preferred settings. As developer, I do fresh installs way more often than normal users, so this really increases my productivity, if I don't have to re-setup everything all the time. Granted I could have hidden it in some other way, but I didn't have a good idea at the time and I can spend my time on more meaningful things as well.

What if you changed it to say "default settings" or "developer default settings" or something of the sort?

**Comment by SpiritCroc** [comment]
> What if you changed it to say "default settings" or "developer default settings" or something of the sort?

I'd rather hide it better then changing the name.
I'm a bit tired of this discussion right now (it amazes me what kind of apparently serious issues people have with some small aspect that can make the dev-ing more fun and motivate me more to pursue this hobby... I had to deal with some very troublesome user yesterday so my mood is already a bit damaged, sorry not your fault), maybe I'll hide it for non-internal builds later.
