### ISSUE TITLE
Duplicate "Settings" button

### ISSUE THREAD

**Issue by foxyseta** [SchildiChat/SchildiChat-android#220]
**Describe the bug**
The "Settings" menu can be opened by touching the user's propic at the top left of the main screen. So the "Settings" entry in the top right menu is redundant

**Expected behavior**
There should be no "Settings" entry in the top right menu.

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: LineageOS 20

**Additional context**
 - App version: 1.6.8.sc74[40101242](F-86317190)
 - Store: F-Droid
 - Homeserver: teapot.ovh
 - Related labs settings: all of them. The issue still persists when disabling them
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: no

**Upstream relevance**
 - Does this issue exist in Element Android? No

**Comment by SpiritCroc** [comment]
This is on purpose. Opening settings by clicking on the profile picture is not intuitive to me and some other users, so having it in the menu can be seen as an accessibility feature. I'd rather remove the functionality from the profile picture, but then people switching from Element could get confused. Having multiple ways to reach settings doesn't really hurt, especially since the clicking-on-the-profile thing is not apparent by text or icon, so anyone can use the button which they prefer.
