### ISSUE TITLE
Cant leave recovery key page

### ISSUE THREAD

**Issue by Wandelstock** [SchildiChat/SchildiChat-android#3]
![Screenshot_20200809-110406.png](https://user-images.githubusercontent.com/58773587/89728788-34f55480-da30-11ea-97dd-95f16d8ed01e.png)

I must force stop the app to leave this page.

**Comment by SpiritCroc** [comment]
Does the back button not work? It does for me, if it does not for you, how did you enter this screen?

**Comment by Wandelstock** [comment]
The back button didnt worked. I tried my backup key, but it wasnt recognized, so i tried to backout what want working

**Comment by SpiritCroc** [comment]
Since I don't remember changing anything here, it would be great if you could
- Document the exact steps to reproduce this issue from a fresh install
- Try out if this issue happens on Element (v1.0.4) as well
If it happens in Element, you can check their bug tracker if the issue already exists or create a bug report there
If it does not happen with Element, post the exact steps to reproduce here so I can try them out.

**Comment by Wandelstock** [comment]
It only works on certain servers. And the one i tried had problems this weekend. Now it works fine, you can close this issue.

**Comment by SpiritCroc** [comment]
Interesting, thanks for reporting!
