### ISSUE TITLE
Wider bubbles for both sides theme

### ISSUE THREAD

**Issue by p1gp1g** [SchildiChat/SchildiChat-android#42]
**Is your feature request related to a problem? Please describe.**
I think the bubble size in group rooms can be optimized. The bubbles are always the same weight but not for peers in group rooms (with bubbles, both sides)

**A solution**
Making the bubble wider for peers on group rooms. It could be as long as the others or a few pixels less to be sure to have a difference with our own messages.

**Another solution**
Our own profile picture on the right of our messages and bubbles until the end (like on fluffychat). It is the opposite intent to see who's speaking. This solution is actually putting text more in the middle of the screen* and making read more comfortable. But to unify with DM (1:1), it would require to do the same on it.

*A lot of messages are shorter than the screen width, so they stay close to the beginning of the bubble.

**Comparison**
The first is fast to do, and require less changes, the second would be more comfortable.

**Additional context**
Here is today's length :
![bubbles](https://user-images.githubusercontent.com/31284753/104655403-fe49f700-56bd-11eb-8418-aeccb77dcb70.png)

**Comment by SpiritCroc** [comment]
Your solution 2 would actually be easier to implement, since this is what SchildiChat did before, and if I remember correctly, does only require minor changes in the code to "enable" it again. That said, I don't think that's a good idea (at least it will not make everyone happy): the own avatar was removed on purpose to save space for messages, while not hiding any relevant information for understanding the chat history (compare e.g. https://github.com/SchildiChat/SchildiChat-android/issues/7).

I'll probably play around with message bubble widths a little more to make them more similar in group chats. Concerning your solution 2, I could maybe make a setting "Don't hide sender avatar in DMs and for own messages" or similar, but I'd prefer to not do it if not necessary, since this would another case for testing, some more code complexity, and an additional setting for users that many probably don't need.

**Comment by p1gp1g** [comment]
Actually, what I meant wouldn't reduce message space (see below). But I understand if you prefer not to do that (it is just another way to handle intent etc.)

The 1st is today, the 2nd, something close to what I described in the first solution and the 3rd is the solution with profil picture.
![bubbles2](https://user-images.githubusercontent.com/31284753/104809792-06a24f00-57f0-11eb-9283-c85d53594dbe.png)

**Comment by SpiritCroc** [comment]
I see. I'm not a fan of having the bubbles closer to the edge of the receiver than the sender, though.
