### ISSUE TITLE
ASK: how i can compile?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [SchildiChat/SchildiChat-android#47]
how i can compile that whitout android studio or visual studio?

**Comment by SpiritCroc** [comment]
The recommended way to compile is Android Studio.
You might however also be able compile over the command line using `./gradlew assemble` or some similar command.
Since both ways are well-known standards for Android app development, you can use publicly available information on how to set up a build environment ([just search the Internet](https://developer.android.com/studio/build/building-cmdline)).
