### ISSUE TITLE
piwik

### ISSUE THREAD

**Issue by Hobby-Student** [SchildiChat/SchildiChat-android#5]
Hi there,

I think you did an amazing job. I know many people who don't want to use Element because of the design. They just stick to WhatsApp.
The only thing I found on my first look at your code:
https://github.com/SpiritCroc/SchildiChat-android/blob/db6e85b1209db93a4b638fc1e4227c115bd47ac0/vector/src/main/res/values/config.xml#L8
https://github.com/SpiritCroc/SchildiChat-android/blob/db6e85b1209db93a4b638fc1e4227c115bd47ac0/vector/src/main/res/values/config.xml#L9

Why not just use "localhost" to prevent security concerns?
I would just leave it default to poin to riot.im.

The lack of experience and free time these days won't let me dive deeper in "theming" an android app. But I'll try to support your work.

**Comment by SpiritCroc** [comment]
Right, localhost is a good idea, I'll do that.
I don't think it's a good idea to let them point to riot.im, since I want to avoid bug reports which are caused by my app to appear on the upstream bugtracker. Reporting bugs that are caused by some forks to developers of the upstream code is a waste of their time and should be avoided. Actually, both of these strings should not be used anywhere in SchildiChat right now, but I changed them anyway just to be sure in case some upstream merges change something that I don't see right away.
