### ISSUE TITLE
Patch features back to Element

### ISSUE THREAD

**Issue by notramo** [SchildiChat/SchildiChat-android#6]
Did you tried to open PR to upstream with some features? For example, a switch in the settings for chat bubbles would be cool in Element. Also, applying it upstream would reduce the fork maintenance work.

**Comment by SpiritCroc** [comment]
I haven't opened any PRs yet, I might do so in the future if I have enough time and motivation to bring some of my changes into a merge-able form.

I won't PR the message bubbles anytime soon, since I doubt they would merge it. In fact, I wouldn't merge it if I were them. They have some code generation going on which I don't fully understand, so I wasn't able to achieve what I was trying to in a clean manner (Maybe it's not possible? It would be without the code generation, though...), so the message bubble code is nothing I consider ready for bigger projects like Element, when considering cleanliness and maintainability.

**Comment by notramo** [comment]
You could ask the main team to help you understand the code generation stuff.
Do you plan to fix bugs too, or only add new features? I am asking because there are some bugs that are fatal to UX. For example, on some devices calls aren't working at all. This can cause such a bad experience for non-techie users that they stop using Matrix, because despite other platforms are not that secure, they are usable at last.

**Comment by SpiritCroc** [comment]
Basically, since I do this in my free time, I do whatever I feel like with it.
It makes no sense for me to hunt bugs in Element (or possibly your homeserver setup?) that I haven't experienced myself yet.
