### ISSUE TITLE
Room search and suggestions 

### ISSUE THREAD

**Issue by AnisTaluqdar** [SchildiChat/SchildiChat-android#73]
How can I join in a room? There have not any option to join in the room by searching also there have not suggestions.

**Comment by SpiritCroc** [comment]
If you click on the plus in the bottom right corner of the chat overview, you can select "Rooms". Assuming you have not enabled the "easy mode" during setup / in settings, you should now be able to see some rooms that are published in the public room directory of your homeserver, if there are any. Since many rooms are published on the matrix.org homeserver, but possibly not on your homeserver's room directory, you can also click the three-dots-menu button in the top right and select "Change network". Here, you can choose the matrix.org room directory. After clicking this, there should be a searchable list of public rooms on that homeserver, which hopefully contains some interesting rooms for you.
